export const DAYS_PER_YEAR = 365;
export const DEFAULT_MAX_AGE_GAP_YEARS = 1;
export const DEFAULT_MAX_AGE_GAP_DAYS = DEFAULT_MAX_AGE_GAP_YEARS * DAYS_PER_YEAR;
export const MAX_MATCHES_PER_WRESTLER = 5;
